//! Generates the qrc resource declaration from whatever is on disk.
//!
//! The QML tree and the vendored assets are compiled into the binary, so a
//! source checkout and a packaged AppImage both find them without assuming
//! anything about the layout around them. Enumerating the files here rather
//! than listing them in a macro call means adding a QML file is just adding a
//! file — nobody has to remember to register it.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn collect(dir: &Path, base: &Path, out: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut entries: Vec<_> = entries.filter_map(Result::ok).collect();
    entries.sort_by_key(|e| e.path());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, base, out);
        } else if path.is_file() {
            let relative = path.strip_prefix(base).expect("under base");
            out.push(relative.to_string_lossy().replace('\\', "/"));
        }
    }
}

fn resource(manifest: &Path, dir: &str) -> String {
    let base = manifest.join(dir);
    let mut files = Vec::new();
    collect(&base, &base, &mut files);
    println!("cargo:rerun-if-changed={}", base.display());
    let entries: Vec<String> = files
        .iter()
        .map(|f| format!("        {f:?},"))
        .collect();
    format!(
        "    {dir:?} as {dir:?} {{\n{}\n    }}",
        entries.join("\n")
    )
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    let body = ["qml", "assets"]
        .iter()
        .map(|dir| resource(&manifest, dir))
        .collect::<Vec<_>>()
        .join(",\n");

    // The icon sources are also compiled in as strings: they are recoloured at
    // run time (Lucide draws with `stroke="currentColor"`, which QSvgRenderer
    // does not resolve), so Rust needs the text and not just a qrc entry.
    let icons = manifest.join("assets/icons");
    let mut names = Vec::new();
    collect(&icons, &icons, &mut names);
    let table: Vec<String> = names
        .iter()
        .filter(|f| f.ends_with(".svg"))
        .map(|f| {
            let stem = f.trim_end_matches(".svg");
            let path = icons.join(f);
            format!("    ({stem:?}, include_str!({:?})),", path.to_string_lossy())
        })
        .collect();

    let generated = format!(
        "// @generated by build.rs — do not edit.\n\
         ::qmetaobject::qrc!(pub register_resources,\n{body}\n);\n\n\
         /// Every vendored Lucide icon, by name, as SVG source.\n\
         pub static ICON_SOURCES: &[(&str, &str)] = &[\n{}\n];\n",
        table.join("\n")
    );
    fs::write(out.join("resources.rs"), generated).expect("write resources.rs");
}
